# Generated by Django 4.2.10 on 2025-07-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_governorateshipping_order_governorate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BostaPickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosta_pickup_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time_slot', models.CharField(choices=[('10:00 to 13:00', '10:00 to 13:00'), ('13:00 to 16:00', '13:00 to 16:00')], max_length=20)),
                ('pickup_address', models.JSONField(help_text='Address where packages will be picked up')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('number_of_packages', models.PositiveIntegerField(default=0)),
                ('bosta_response_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pickup Request',
                'verbose_name_plural': 'Pickup Requests',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BostaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Bosta API Key', max_length=255)),
                ('api_base_url', models.URLField(default='https://app.bosta.co', help_text='Bosta API Base URL (staging: https://stg-app.bosta.co)')),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=20)),
                ('business_reference', models.CharField(blank=True, help_text='Your business reference for Bosta', max_length=100)),
                ('default_pickup_address', models.JSONField(blank=True, help_text='Default pickup address for your business', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook validation', max_length=255)),
                ('webhook_url', models.URLField(blank=True, help_text='Your webhook URL for Bosta notifications')),
                ('auto_create_shipments', models.BooleanField(default=False, help_text='Automatically create Bosta shipments for new orders')),
                ('auto_request_pickup', models.BooleanField(default=False, help_text='Automatically request pickup when shipments are created')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bosta Settings',
                'verbose_name_plural': 'Bosta Settings',
            },
        ),
        migrations.CreateModel(
            name='BostaShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bosta_tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bosta_delivery_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('delivery_type', models.IntegerField(choices=[(10, 'Package Delivery'), (20, 'Cash Collection (COD)')], default=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pickup_requested', 'Pickup Requested'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('exception', 'Exception')], default='pending', max_length=20)),
                ('bosta_response_data', models.JSONField(blank=True, help_text='Full response from Bosta API', null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_address', models.JSONField(blank=True, help_text='Pickup address details', null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_collected', models.BooleanField(default=False)),
                ('cod_collection_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bosta_shipment', to='orders.order')),
                ('pickup_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.bostapickuprequest')),
            ],
            options={
                'verbose_name': 'Bosta Shipment',
                'verbose_name_plural': 'Bosta Shipments',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BostaTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Shipment Created'), ('pickup_requested', 'Pickup Requested'), ('picked_up', 'Package Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('returned_to_sender', 'Returned to Sender'), ('cancelled', 'Cancelled'), ('exception', 'Exception Occurred')], max_length=30)),
                ('event_description', models.TextField()),
                ('event_location', models.CharField(blank=True, max_length=200)),
                ('event_timestamp', models.DateTimeField()),
                ('webhook_data', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='shipping.bostashipment')),
            ],
            options={
                'verbose_name': 'Tracking Event',
                'verbose_name_plural': 'Tracking Events',
                'ordering': ('-event_timestamp',),
            },
        ),
    ]
