# Generated by Django 5.2.1 on 2025-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_size_id_orderitem_size_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernorateShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Governorate name', max_length=50, unique=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, help_text='Shipping cost for this governorate in LE', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this governorate is available for shipping')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Governorate Shipping',
                'verbose_name_plural': 'Governorate Shipping Rates',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='governorate',
            field=models.CharField(blank=True, help_text="Customer's governorate for shipping calculation", max_length=50, null=True),
        ),
    ]
