# Generated by Django 5.2.2 on 2025-06-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='ourbest',
        ),
    ]
