# Generated by Django 5.2.3 on 2025-06-27 03:21

import storage.github_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, storage=storage.github_storage.GitHubMediaStorage(), upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=storage.github_storage.GitHubMediaStorage(), upload_to='products/details/%Y/%m/%d'),
        ),
    ]
